import type { ThesisSeed } from "./theses";
import type { EvidenceLink } from "./evidence";
import type { SourcePost } from "@/lib/source-post";

export type CuratedEvidence = EvidenceLink & { sourcePost?: SourcePost };

// Original post verified against the FxTwitter public mirror at 2026-09-15T08:45:14Z:
// author @naval, posted 2026-09-13T04:14:57Z, text byte-identical apart from a trailing
// space before the line break. Re-check with `pnpm tsx scripts/verify-source-posts.ts`.
// The post author is the source of the question, never the author of this portfolio.
export const CURATED_THESES: ThesisSeed[] = [{
  slug: "ai-liability-favors-big-cloud",
  title: "Nobody knows who is liable for AI. That is the moat.",
  claim: "Nobody knows who is liable for AI. That is the moat.",
  category: "Technology",
  summary: "Naval asked who is liable when AI causes harm. Nobody has answered, and unanswered liability is a reason to buy from whoever is large enough to absorb it.",
  rationale: "Naval asks who is liable when AI causes harm. Our interpretation: that uncertainty could push enterprise buyers toward Microsoft, Google and Amazon. Microsoft and Google have already offered conditional protection against some copyright claims; AWS sells tools to filter harmful model outputs. These are different responses to risk, not blanket protection against AI harm. The investment bet is that procurement favors established vendors and their paid platforms. That is an inference about future demand, not something Naval said or the sources prove.",
  counterargument: "The companies with the deepest pockets may become the biggest targets. Paying for claims and safeguards can cost more than the customers they attract. Copyright protection does not answer Naval's question about injury or death. And buying three huge companies is an imprecise way to trade one issue: advertising, retail, capital spending and valuation could overwhelm any benefit from enterprise trust.",
  changeMyMind: "At the next two quarterly earnings reviews, look for evidence that customers choose smaller AI vendors despite liability concerns, or that legal and safety costs outgrow the revenue attributed to enterprise AI. If neither side provides measurable evidence, keep the causal thesis unproven even if this basket beats the market.",
  horizonLabel: "Review in 6 months",
  reviewDate: "2027-03-15",
  weightRationale: "Near-equal weights avoid pretending we know which vendor captures the demand. Microsoft's extra percentage point is a rounding choice, not a stronger forecast.",
  constituents: [
    { symbol: "MSFTx", position: 0, weightBps: 3400, role: "Enterprise trust", why: "Microsoft has explicitly offered conditional copyright protection for eligible commercial AI customers. The bet is that established procurement relationships help turn that reassurance into paid adoption.", limitation: "The commitment covers specified IP claims under conditions, not every form of AI harm. Liability costs and heavy infrastructure spending could outweigh additional demand." },
    { symbol: "GOOGLx", position: 1, weightBps: 3300, role: "Model + platform", why: "Google has offered protection covering training-data and generated-output IP claims for specified services. Owning models and the cloud platform gives it more than one place to sell enterprise AI.", limitation: "The protection is conditional and limited. Search advertising dominates the parent company's economics, so this token is a broad, indirect expression of enterprise AI trust." },
    { symbol: "AMZNx", position: 2, weightBps: 3300, role: "Risk controls", why: "Amazon Bedrock offers configurable guardrails for model inputs and outputs. The bet is that enterprises buy managed controls through an existing AWS relationship rather than assemble everything themselves.", limitation: "Guardrails reduce certain risks; they do not guarantee safe outputs or transfer all liability. Retail and the rest of AWS can move this holding independently of the thesis." },
  ],
}, {
  slug: "contracted-capex-pays-the-supplier-first",
  title: "The capex is already contracted. The supplier is paid first.",
  claim: "The capex is already contracted. The supplier is paid first.",
  category: "Technology",
  summary: "Multi-year datacenter commitments are signed long before the revenue they are meant to produce arrives. The cash reaches whoever sells the capacity well before it reaches the buyer's earnings.",
  rationale: "Amit argues the spending is contracted rather than speculative, and lists the commitments to make the point. Our reading is narrower than his: whether or not the buildout pays off for the buyers, the cash leaves their balance sheets on a schedule already agreed, and it lands on whoever sells the hardware and the capacity. That is a claim about sequence, not about whether AI earns its cost. He named four spenders; he did not choose these assets, set these weights, or make our timed call.",
  counterargument: "Being paid first is not the same as being paid durably. Contracted orders can be renegotiated, delayed, or filled by a competitor, and a supplier priced for permanent scarcity is priced for a cycle that has always ended. If the buyers conclude the returns are not there, the next round of contracts simply is not signed.",
  changeMyMind: "Two consecutive quarters in which a major hyperscaler guides capex down, or a large contracted order is publicly cancelled or repriced.",
  horizonLabel: "Review in 12 months",
  reviewDate: "2027-09-17",
  weightRationale: "Weighted toward the supplier because the claim is about who receives the money first, not about who ultimately profits from it.",
  constituents: [
    { symbol: "NVDAx", position: 0, weightBps: 4000, role: "The supplier", why: "The largest single recipient of committed datacenter spending, and so the clearest expression of a claim about who is paid first.", limitation: "Concentration in one product cycle and one customer set. Those same customers are funding alternatives, and a supplier priced for scarcity is the first thing repriced when scarcity ends." },
    { symbol: "MSFTx", position: 1, weightBps: 3000, role: "Spender and reseller", why: "Sits on both sides: it commits the capex and rents the resulting capacity out, which makes it a partial hedge against the supplier leg rather than a second copy of it.", limitation: "Depreciation at this scale lands on its own margins, so being on both sides cuts in both directions." },
    { symbol: "AMZNx", position: 2, weightBps: 3000, role: "The other buyer", why: "The second large committed buyer named in the post, and the one whose earnings are least dominated by AI, which stops the basket being one bet expressed three times.", limitation: "Retail and the rest of AWS can move this holding for reasons unrelated to the claim." },
  ],
}, {
  slug: "appetite-medicine-becomes-everyday-care",
  title: "Appetite medicine becomes everyday healthcare",
  claim: "Appetite medicine becomes everyday healthcare",
  category: "Health",
  summary: "Metabolic medicines that change appetite are moving from a niche prescription toward routine care. If access, supply and delivery keep improving, the treatment market grows with them.",
  rationale: "The FDA extended one of these medicines to reducing the risk of serious heart problems in a defined group of adults with obesity or overweight, which moves it from a weight treatment toward a cardiovascular one. Lilly's published pipeline shows how much development is still aimed at the same field. Our reading: more eligible patients reach treatment as supply, reimbursement and easier forms of delivery improve, and the two companies that lead the field sell into that larger market. Approval, trial results and commercial economics are different facts; the sources establish the first two, not the third.",
  counterargument: "A bigger market can come with lower prices. Governments and insurers push net prices down, many patients stop treatment within a year, competitors and cheaper copies arrive, and a safety finding could change everything. Both companies are already priced for a lot of this growth, so patients can multiply while shareholders earn little.",
  changeMyMind: "Across the next two earnings cycles, prescriptions keep rising while net prices and the share of patients who stay on treatment both fall; or a material safety or regulatory setback for the class.",
  horizonLabel: "Review in 12 months",
  reviewDate: "2027-09-24",
  weightRationale: "Equal weights: the claim is that the treatment market grows, not which of the two leaders wins more of it.",
  constituents: [
    { symbol: "LLYx", position: 0, weightBps: 5000, role: "The broadest pipeline", why: "Eli Lilly sells leading metabolic medicines and publishes a deep pipeline in the same field, so it gains if the market widens beyond today's patients.", limitation: "Priced for a great deal of growth already, and exposed to price cuts, supply limits and competition. Its other medicines also move the stock." },
    { symbol: "NVOx", position: 1, weightBps: 5000, role: "The first mover", why: "Novo Nordisk built the category and holds the cardiovascular indication the FDA approved, which is the clearest step from weight loss toward everyday care.", limitation: "It has lost ground to competition before, and a Danish company's US-listed token also moves with currency and its own guidance." },
  ],
}, {
  slug: "spending-a-trillion-is-the-easy-part",
  title: "Spending a trillion is the easy part",
  claim: "Spending a trillion is the easy part",
  category: "Technology",
  summary: "Announced capex becomes depreciation on somebody's income statement for years afterwards. The question is not who can spend it, but who can carry it.",
  rationale: "Epoch AI measures the spending trajectory, not the returns on it. Our reading is that at this scale the binding constraint stops being access to capital and becomes the ability to absorb depreciation without the earnings line breaking, which favours businesses with large, unrelated profit pools to bury it in. Epoch AI published the measurement; the portfolio interpretation and the timed prediction are ours alone.",
  counterargument: "This is an argument for size, and size is already priced. If the assets have shorter useful lives than assumed, a large profit pool delays the damage rather than preventing it — and every holding here is exposed to exactly the same mistake at the same time.",
  changeMyMind: "A major operator shortening the assumed useful life of its AI hardware, or writing down datacenter assets.",
  horizonLabel: "Review in 12 months",
  reviewDate: "2027-09-17",
  weightRationale: "Weighted by depth of unrelated profit, because that is the thing the claim says is scarce. It was evenly weighted and therefore identical to another basket in this catalogue, which made two different arguments into one purchase.",
  constituents: [
    { symbol: "MSFTx", position: 0, weightBps: 4500, role: "Deepest profit pool", why: "The largest established software earnings base to absorb depreciation against, plus a rental business that converts the assets into revenue directly.", limitation: "Also the largest committed spender, so it has the most to absorb." },
    { symbol: "GOOGLx", position: 1, weightBps: 3500, role: "Advertising cushion", why: "Search advertising is a profit pool almost unrelated to the buildout, which is precisely the cushion this claim is about.", limitation: "That independence cuts both ways: the holding can move on advertising news that says nothing about this thesis." },
    { symbol: "AMZNx", position: 2, weightBps: 2000, role: "The hardest case", why: "Included deliberately as the thinnest-margin operator, which is where this claim would fail first if it is wrong.", limitation: "Retail earnings dominate and can swamp the signal entirely." },
  ],
}, {
  slug: "the-ai-money-is-private-now",
  title: "The companies winning this cycle never listed",
  claim: "The companies winning this cycle never listed",
  category: "Technology",
  summary: "The two labs setting the pace have no ticker. Tokenized pre-IPO exposure is the only way a public-market buyer can hold them at all — and it comes with an issuer who can take it away.",
  rationale: "Every listed AI basket is a bet on the suppliers and the buyers of compute, because the companies actually building the frontier models are private. That is a gap in what a public-market investor can express, not a judgement that the private companies are better businesses. PreStocks tokens close the gap: they reference economic exposure to OpenAI and Anthropic, and they settle on Solana against USDC like anything else in this catalogue. The listed leg is here to keep the basket honest — if the private names are mispriced by their own thin books, the supplier leg is the part with a public price to check them against.",
  counterargument: "The wrapper is the risk, and it is larger than the companies. The issuer holds permanent delegate, freeze and pause authority over both pre-IPO mints from a single key, and its terms reserve the right to claw back or compulsorily redeem a holding at a price it sets — which it says may be nil — with no notice and no appeal. There is no named legal entity behind it, no proof of reserves, and no confirmed retail redemption path. Every transfer pays a 0.5% fee the issuer can raise on tokens already held. On top of that the books are thin enough that the market price sits at a persistent premium or discount to the issuer's own reference price, so a buyer is not buying at net asset value. It is entirely possible to be right about OpenAI and Anthropic and still lose everything here.",
  changeMyMind: "Any of: a public clawback, freeze or forced redemption of a holder's PreStocks position; the transfer fee being raised; or the market price staying more than 15% from the issuer's reference price for a month. Any one of those makes the wrapper, not the companies, the thing being traded.",
  horizonLabel: "Review in 6 months",
  reviewDate: "2027-03-18",
  weightRationale: "The listed leg is a quarter of the basket and is not a conviction weight — it is the only holding here with a public market price, and it is sized to be a reference point rather than a hedge. Between the two private names, the larger weight goes to the deeper book, because at this size liquidity is the difference between a position and a trap.",
  constituents: [
    { symbol: "OPENAI", position: 0, weightBps: 4000, role: "The frontier, unlisted", why: "The company most associated with this cycle and entirely inaccessible on a public exchange. Its token has the deepest book of the pre-IPO set, which is what makes a basket-sized position fillable at all.", limitation: "The issuer can freeze, claw back or compulsorily redeem this token at a price it sets, and its terms say that price may be nil. Its balance also carries a scaled-UI multiplier, so the displayed quantity is not the raw one." },
    { symbol: "ANTHROPIC", position: 1, weightBps: 3500, role: "The other frontier lab", why: "The second name in the same race, and the one whose revenue is weighted toward enterprise rather than consumer, so the two legs are not the same bet twice.", limitation: "Same issuer, same single key holding permanent delegate and freeze authority over it. Concentrating two of three holdings with one issuer is the concentration risk that matters here, and it is deliberate rather than overlooked." },
    { symbol: "NVDAx", position: 2, weightBps: 2500, role: "The public price check", why: "The one holding with a continuous public market behind it. It is here so the basket has a reference that cannot be set by the issuer of the other two.", limitation: "It is also the most widely held AI asset in the world, so it contributes little that a reader does not already own elsewhere." },
  ],
}];

export const CURATED_EVIDENCE: Record<string, CuratedEvidence[]> = {
  "the-ai-money-is-private-now": [
    { url: "https://prestocks.notion.site/terms-of-service", title: "PreStocks Terms of Service", source: "PreStocks", publishedAt: "2026-09-08", relevance: "The issuer's own statement of what it can do to a holding: freeze, claw back, burn, or compulsorily redeem at a value it determines, which it says may be nil, without notice or appeal. It also states that holders acquire no shareholder rights and no claim on the assets behind the token, and that US persons may not use the service. This is the primary risk in the basket and it is documented by the issuer, not inferred by us.", kind: "primary" },
    { url: "https://prestocks.com/products", title: "PreStocks products and mint addresses", source: "PreStocks", publishedAt: null, relevance: "The issuer's list of live tokens and their Solana mint addresses. Each mint in this basket was read from mainnet and its on-chain metadata symbol matched against this list before being allowlisted; the page is the cross-check, never the source of truth.", kind: "primary" },
    { url: "https://solscan.io/token/PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF", title: "OPENAI mint on Solana", source: "Solscan", publishedAt: null, relevance: "The mint account itself, where the Token-2022 extensions can be read directly: permanent delegate, freeze authority, pausable config, the 0.5% transfer fee and the scaled-UI multiplier. Everything the counterargument claims about issuer power is verifiable here rather than taken on trust.", kind: "primary" },
    { url: "https://solscan.io/token/Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw", title: "ANTHROPIC mint on Solana", source: "Solscan", publishedAt: null, relevance: "The second pre-IPO mint, carrying the same authorities under the same key as the first. This is the evidence for the concentration risk named in the weight rationale.", kind: "primary" },
  ],
  "ai-liability-favors-big-cloud": [
    { url: "https://x.com/naval/status/2098988781592547683", title: "Naval asks who is liable for AI harm", source: "Naval on X", publishedAt: "2026-09-13", relevance: "The question that inspired this basket. Naval does not name these stocks, recommend this allocation, or make our timed prediction.", kind: "primary",
      sourcePost: { url: "https://x.com/naval/status/2098988781592547683", author: "Naval", handle: "@naval", text: "On the way to killing all of us, AI will likely kill some of us.\n\nIn that case, who’s liable?", postedAt: "2026-09-13T04:14:57.000Z", verifiedAt: "2026-09-15T08:45:14.000Z" } },
    { url: "https://blogs.microsoft.com/on-the-issues/2023/09/07/copilot-copyright-commitment-ai-legal-concerns/", title: "Microsoft’s Customer Copyright Commitment", source: "Microsoft", publishedAt: "2023-09-07", relevance: "Microsoft announced conditional copyright protection for commercial AI customers, later expanding it to Azure OpenAI. This establishes a concrete response to buyer concerns; it does not demonstrate an effect on revenue or cover all AI harm.", kind: "primary" },
    { url: "https://cloud.google.com/blog/products/ai-machine-learning/protecting-customers-with-generative-ai-indemnification", title: "Protecting customers with generative AI indemnification", source: "Google Cloud", publishedAt: "2023-10-13", relevance: "Google describes training-data and generated-output IP protections with conditions. Evidence that enterprise risk is part of its product proposition, not evidence that this stock will outperform.", kind: "primary" },
    { url: "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html", title: "Amazon Bedrock Guardrails", source: "AWS documentation", publishedAt: null, relevance: "AWS documents configurable filters and controls for model inputs and outputs. This supports the managed-controls role in the basket, not an assumption that AWS absorbs every liability.", kind: "primary" },
    { url: "https://www.microsoft.com/licensing/terms/product/ForOnlineServices/OVOVS", title: "Microsoft online services terms: limits of copyright protection", source: "Microsoft Product Terms", publishedAt: null, relevance: "The protection is conditional on safeguards, rights to inputs and other requirements, with excluded claims. These limits challenge the leap from copyright indemnity to protection against the kinds of harm in Naval's question.", kind: "primary", supportsCounterargument: true },
  ],
  "appetite-medicine-becomes-everyday-care": [
    { url: "https://www.fda.gov/news-events/press-announcements/fda-approves-first-treatment-reduce-risk-serious-heart-problems-specifically-adults-obesity-or", title: "FDA approves first treatment to reduce risk of serious heart problems specifically in adults with obesity or overweight", source: "U.S. Food and Drug Administration", publishedAt: "2024-03-08", relevance: "Extends Wegovy to reducing the risk of cardiovascular death, heart attack and stroke in adults with established heart disease and obesity or overweight. It establishes a specific approved indication in a defined group, not a universal treatment claim or anything about pricing or profit.", kind: "primary" },
    { url: "https://www.lilly.com/science/research-development/pipeline", title: "Lilly research and development pipeline", source: "Eli Lilly and Company", publishedAt: null, relevance: "The company's own list of medicines in development, showing how much of it targets metabolic disease. A pipeline is intent and trial stage, not approval or future revenue; several programmes will fail.", kind: "primary" },
  ],
  "contracted-capex-pays-the-supplier-first": [
    { url: "https://epoch.ai/data-insights/hyperscaler-capex-trend", title: "Hyperscaler capex has quadrupled since GPT-4's release", source: "Epoch AI", publishedAt: null, relevance: "Measures combined capex at Alphabet, Amazon, Meta, Microsoft and Oracle growing about 72% a year since Q2 2023. Epoch states its own limits: finance leases may be understated, operating leases are excluded, companies define capex differently, and the share that is specifically AI is not disclosed. It establishes that the spending is large and rising; it does not establish who profits from it.", kind: "primary" },
    { url: "https://epoch.ai/data-insights/hyperscaler-capex-vs-cash-flow", title: "Hyperscaler capex on track to overtake operating cash flow", source: "Epoch AI", publishedAt: null, relevance: "Projects aggregate cash capex overtaking operating cash flow around Q3 2026, with capex growing about 70% a year against 23% for cash flow. Epoch calls these simple extrapolations, notes the crossover moves between Q2 and Q4 2026 depending on the fitting window, and does not model whether the returns justify the spending. This is the strongest published case against both baskets: spending that outruns cash generation is the mechanism by which the buildout stops.", kind: "primary", supportsCounterargument: true },
    { url: "https://x.com/amitisinvesting/status/1965184088089714706", title: "Amit argues AI capex is contracted, not speculative", source: "amitisinvesting on X", publishedAt: "2026-09-08", relevance: "The post that prompted this basket. He names four spenders and argues the commitments are real; he does not recommend this allocation, choose these weights, or make our timed call.", kind: "primary",
      sourcePost: { url: "https://x.com/amitisinvesting/status/1965184088089714706", author: "amit", handle: "@amitisinvesting", text: "So once again, someone explain to me how exactly AI capex is all a bubble?\n\n$NBIS got a $20B deal for 5 years.\n\nTheir market-cap was $15B at end of day.\n\nMicrosoft, a hyperscaler, already is spending massive amounts on capex.\n\nThe AI bears will tell you the entire capex lifecycle is done and peaked because $NVDA is down $10 after earnings, as if a company never fell after earnings.\n\nThen Nadella whips out $20B after hours for more datacenter/cloud/compute buildout…\n\nZucks is ready to “conservatively” spend $600B on capex by the end of 2028. \n\nAmazon, Microsoft, Meta and Google are expected to spend $465 billion on capex in 2026, up 21% YoY. \n\nWhat are we talking about? \n\nHow can someone reasonably say it’s all a bubble? \n\nAt this point it feels like people wanting to just say AI is pointless for the sake of saying it to “call the top” vs actually analyzing the rate of growth, spend, and ROI that we are seeing from AI. \n\n$AMZN $META $MSFT $GOOGL", postedAt: "2025-09-08T22:42:52.000Z", verifiedAt: "2026-09-17T04:40:42.419Z" } },
  ],
  "spending-a-trillion-is-the-easy-part": [
    { url: "https://epoch.ai/data-insights/hyperscaler-capex-trend", title: "Hyperscaler capex has quadrupled since GPT-4's release", source: "Epoch AI", publishedAt: null, relevance: "Measures combined capex at Alphabet, Amazon, Meta, Microsoft and Oracle growing about 72% a year since Q2 2023. Epoch states its own limits: finance leases may be understated, operating leases are excluded, companies define capex differently, and the share that is specifically AI is not disclosed. It establishes that the spending is large and rising; it does not establish who profits from it.", kind: "primary" },
    { url: "https://epoch.ai/data-insights/hyperscaler-capex-vs-cash-flow", title: "Hyperscaler capex on track to overtake operating cash flow", source: "Epoch AI", publishedAt: null, relevance: "Projects aggregate cash capex overtaking operating cash flow around Q3 2026, with capex growing about 70% a year against 23% for cash flow. Epoch calls these simple extrapolations, notes the crossover moves between Q2 and Q4 2026 depending on the fitting window, and does not model whether the returns justify the spending. This is the strongest published case against both baskets: spending that outruns cash generation is the mechanism by which the buildout stops.", kind: "primary", supportsCounterargument: true },
    { url: "https://x.com/EpochAIResearch/status/2060076222873526506", title: "Epoch AI: hyperscaler capex on trend for $770B in 2026", source: "Epoch AI on X", publishedAt: "2026-09-14", relevance: "The measurement this basket reasons from. Epoch AI publishes the capex trajectory; the portfolio interpretation and the timed prediction are ours.", kind: "primary",
      sourcePost: { url: "https://x.com/EpochAIResearch/status/2060076222873526506", author: "Epoch AI", handle: "@EpochAIResearch", text: "Hyperscaler capital expenditures came in on trend in Q1 2026, continuing the trajectory that projects them spending $770 billion this year and over a trillion dollars in 2027.", postedAt: "2026-05-28T19:10:20.000Z", verifiedAt: "2026-09-17T04:40:43.220Z" } },
  ],
};
